name: CI
on:
  push:
    branches: [test]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.SSH_SECRET }}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Sync project files
        run: rsync -avzr -e 'ssh -o StrictHostKeyChecking=no' --delete ${GITHUB_WORKSPACE}/build/ git@68.79.55.155:/root/Caddy/juzi-official-site/
