name: build
on:
  push:
    branches:
      - test
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repositories
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: cn-northwest-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16.7.0
          registry-url: https://npm.pkg.github.com/
          scope: '@juzibot'

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: my-ecr-repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          export PACKAGE_VERSION=${{ github.sha }}
          npm run docker-ci
    outputs:
      version: ${{ github.sha }}
